---
title: "FAQs"
callout-appearance: minimal
callout-icon: false
callout-collapse: true
---

## Workshop

::: {.callout-tip collapse="true"}
## Who is the intended audience for this workshop?

This workshop is designed for graduate students, postdocs, or faculty who are planning a demographic field study with the intention of building IPMs or those who already have census data and want to construct an IPM.
:::

::: {.callout-tip collapse="true"}
## When will the workshop be held this year?

August 10–12, 2026 (Monday-Wednesday). Participants will arrive on the evening before (Sunday August 9) and depart the morning after (Thursday August 13).
:::

::: {.callout-tip collapse="true"}
## Where will the workshop be held?

The workshop will be hosted by [Rocky Mountain Biological Laboratory](https://www.rmbl.org/), a field station in the Rocky Mountains located in the town of Gothic near Crested Butte, Colorado.
:::

::: {.callout-tip collapse="true"}
## How many participants will there be?

We are anticipating 10-12 participants this year.
:::

::: {.callout-tip collapse="true"}
## Will the workshop be run in future years?

We anticipate offering the workshop again in 2027.
:::

<!-- ## Application -->

<!-- ::: {.callout-tip collapse="true"} -->
<!-- ## How do I apply? -->

<!-- Please follow the instructions [here](apply.qmd). -->
<!-- ::: -->

<!-- ::: {.callout-tip collapse="true"} -->
<!-- ## When is the application deadline? -->

<!-- The deadline to receive full consideration is **April 8, 2026**. If you are interested but need additional time, please email Amy Iler. -->

<!-- We will continue accepting applications after the review date if slots remain open. -->
<!-- ::: -->

<!-- ::: {.callout-tip collapse="true"} -->
<!-- ## When will I hear back about whether I have been invited to participate? -->

<!-- We aim to send emailed invitations by **late** **April**. -->
<!-- ::: -->

<!-- ::: {.callout-tip collapse="true"} -->
<!-- ## If I receive an invitation to participate, when do I need to decide whether to accept? -->

<!-- Please let us know **as soon as you can** so we can begin planning for your participation or to make the slot available to an alternate. The last date to accept and confirm that you have your flights booked is **April 15, 2026**. -->
<!-- ::: -->

## Cost, Housing & Dining

::: {.callout-tip collapse="true"}
## How much does the workshop cost?

The workshop fee is \$565, which includes on-site lodging and all meals in the dining hall but does not include travel to RMBL.
:::

::: {.callout-tip collapse="true"}
## Is financial support available?

We have funding from the National Science Foundation to provide financial support to a limited number of participants based on financial need. To allow us to maximize participation, we ask that you make an effort to self-fund your participation through your PI’s grants, your home institution’s resources, or other funding sources (e.g., the American Society of Naturalist’s regional conference and workshop travel grants, Sigma Xi, etc.).
:::

::: {.callout-tip collapse="true"}
## Are meals provided?

Yes, meals will be provided in the RMBL Dining Hall during the workshop. Please see [Dining at RMBL](https://www.rmbl.org/visit-rmbl/dining-hall/).
:::

::: {.callout-tip collapse="true"}
## What are the lodging accommodations?

The workshop fee includes on-site lodging in cabins at the Rocky Mountain Biological Lab. RMBL is built from the remains of a late 1800’s silver-mining town. Most participants will be staying in renovated but rustic cabins built in the 1960’s through 1990’s. See [here](https://www.rmbl.org/field-station-info/housing/) for more information.
:::

## Travel & Packing

::: {.callout-tip collapse="true"}
## How do I get to the workshop?

Participants are responsible for booking and paying for their own travel. We anticipate that most participants will fly into Denver, then travel by intercity bus from Denver to Crested Butte. There is a closer airport in Gunnison, CO, but cancellations due to heat and thunderstorms are common. We welcome any questions you may have about travel or logistics (email [ailer\@chicagobotanic.org](mailto:ailer@chicagobotanic.org)).

The Rocky Mountain Biological Lab (RMBL) is located in the town of Gothic which is about 30 minutes from Crested Butte and a \~5 hour drive from the Denver airport.

We recommend flying through Denver and taking the intercity bus to Crested Butte. Book your flight to arrive before 11am Mountain Time. A light rail train runs directly from Denver International Airport to the Union Station bus terminal (\~45 min duration; 1701 Wynkoop St.). The bus station is below ground, and the [Bustang Outrider line to Crested Butte](https://ridebustang.com/routes/crested-butte-denver/) departs from the middle of the concourse at Gate B4. The bus departs Denver Union Station at 1:45pm and arrives to Crested Butte at 7:35pm.
:::

::: {.callout-tip collapse="true"}
## Can I arrive a bit early or stay a bit later?

Most likely yes, but you will need to arrange a longer stay with RMBL staff. Please contact us if you'd like help arranging an extended stay.
:::

::: {.callout-tip collapse="true"}
## I see an airport that looks closer than Denver. Can I book my flights through there?

Commercial flights are available into Gunnison, which is about 1 hour away from RMBL. The high mountain setting of this airport causes frequent flight cancellations in summer. This region experiences strong monsoonal thunderstorms. Modestly high temperatures also cause cancellations because the already low air density falls below the minimum needed for airplanes to takeoff and land. **We consider flights through Gunnison to be unreliable** if you need to travel on a specific date or want to avoid unexpected hotel stays en route.

**Aspen is likely not a viable alternative despite being geographically very close to Gothic** (\<20 air miles / \<30 km). The intervening terrain is very rugged Wilderness with high mountain passes with no direct road route. The shortest safe road route around these mountains takes \~3 hours (\>100 miles / \>160 km, about 1/3 of that on dirt roads). There is a [private van shuttle](https://www.crestedbutteshuttle.com/rates) that runs pre-arranged service between Aspen but no public transit option.
:::

## Diversity, Community, Health & Safety

::: {.callout-tip collapse="true"}
## How high is the elevation, and how should I prepare?

Gothic, CO sits at 9,600 ft (2900 m) above sea level. Most people coming from low elevation experience mild symptoms from the reduced availability of oxygen. Best practices include hydrating well and getting enough sleep before and immediately after arriving to high elevation. Consider reducing or avoiding caffeine and alcohol. Individuals who anticipate a harder time adjusting to elevation may consider ascending slowly by arriving to Denver a few days early before ascending to Gothic.

The [CDC offers more detailed guidance to high elevation travel](https://wwwnc.cdc.gov/travel/page/travel-to-high-altitudes).
:::

::: {.callout-tip collapse="true"}
## How remote/isolated is RMBL?

The nearest town is Mt. Crested Butte (4 mi / 6.5 km), and the nearest town with services (e.g., gas, pharmacy, grocery store, urgent care clinic) is Crested Butte (8 mi / 13 km). Both towns have emergency services.

The nearest hospital is located in Gunnison (\~1h drive; 35 mi / 57 km).
:::

::: {.callout-tip collapse="true"}
## What is the communications/connectivity situation at RMBL?

There is little to no cell service at RMBL. The vast majority of buildings and major outdoor areas of campus are well-covered by a high-speed wifi network.

Landline phones are located at several locations on campus and are available 24/7 for emergencies.
:::
