---
title: "Schedule"
---

In general, there will be a mix of lecture material, interactive exercises, field excursions, and labs in the hours between breakfast, lunch, and dinner. Meals and the time before breakfast and after dinner will be reserved for socialization and free time for exploration and rest.

The local timezone is Mountain Daylight Time (UTC-6). Sunrise will be \~6:15am and sunset will be \~8:00pm.

Meals will be served in the billy barr Community Center (bbcc).

| Breakfast   | Lunch       | Dinner      |
|-------------|-------------|-------------|
| 7:00-8:00am | Noon-1:00pm | 6:00-7:00pm |

::: callout-important
The workshop schedule below is a rough draft. Additional changes will be made as the workshop plan is finalized.
:::

## Prior to arrival: Prep work

We will have readings and prep-work for you to complete before the workshop begins. This will include things like installing and (re)familiarizing yourself with [R](https://www.r-project.org).

## Sunday August 9, 2026: Arrival Travel Day

+----------------+---------------------------------------------------------------------------------------------------------------------------------------+
|                |                                                                                                                                       |
+================+=======================================================================================================================================+
| before 11:00am | Arrive to Denver International Airport, collect any checked bags, exit airport to RTD "A" line train to Union Station (\~45 min ride) |
+----------------+---------------------------------------------------------------------------------------------------------------------------------------+
| 1:45pm         | Depart to Gunnison on Bustang Outrider, leaves from belowground bus terminal at Union Station (\~6 hour ride)                         |
+----------------+---------------------------------------------------------------------------------------------------------------------------------------+
| \~7:30         | Arrive to Crested Butte on Bustang                                                                                                    |
+----------------+---------------------------------------------------------------------------------------------------------------------------------------+
| 7:45           | Late/quick dinner in Crested Butte                                                                                                    |
+----------------+---------------------------------------------------------------------------------------------------------------------------------------+
| 8:15           | Van transit to RMBL                                                                                                                   |
+----------------+---------------------------------------------------------------------------------------------------------------------------------------+

## Monday August 10: Workshop Day 1

Goals:

- Background and hands-on work on matrix population models & integral projection models

+-----------------------------+------------------------------------------------------+
|                             |                                                      |
+=============================+======================================================+
| 7:00-8:00                   | Breakfast (bbcc)                                     |
+-----------------------------+------------------------------------------------------+
| 8:00-9:00                   | Introductions                                        |
|                             |                                                      |
|                             | Orientation tour                                     |
|                             |                                                      |
|                             | Check-in with RMBL Admin                             |
+-----------------------------+------------------------------------------------------+
| 9:00-noon                   | Population modeling                                  |
|                             |                                                      |
|                             | - Life cycles (Amy)                                  |
|                             |                                                      |
|                             | - Matrix Population Models (Amy)                     |
|                             |                                                      |
|                             | Coding demos                                         |
|                             |                                                      |
|                             | - MPMs with `popbio`                                 |
|                             |                                                      |
|                             | - Simple IPMs with `ipmr`                            |
+-----------------------------+------------------------------------------------------+
| noon-1:00                   | Lunch (bbcc)                                         |
+-----------------------------+------------------------------------------------------+
| 1:00-2:00                   | Tour of RMBL with Science Director, Jennie Reithel   |
+-----------------------------+------------------------------------------------------+
| 2:00-4:30                   | Coding practical                                     |
|                             |                                                      |
|                             | IPM for *Carpobrotus* in `ipmr` (Amy)                |
+-----------------------------+------------------------------------------------------+
| 4:30-6:00                   | Free time for socialization, exploration, rest, etc. |
+-----------------------------+------------------------------------------------------+
| 6:00-7:00                   | Dinner (bbcc)                                        |
+-----------------------------+------------------------------------------------------+
| 7:00-9:00                   | Social gathering at Galena cabin *(optional)*        |
+-----------------------------+------------------------------------------------------+

## Tuesday August 11: Workshop Day 2

Goals:

- Deepen understanding of vital rate modeling concepts, decisions, and implementation

- Begin construction of an IPM for your own data

+----------------------------+----------------------------------------------------------------+
|                            |                                                                |
+============================+================================================================+
| 7:00-8:00                  | Breakfast (bbcc)                                               |
+----------------------------+----------------------------------------------------------------+
| 8:00-9:00                  | Group walk to Kettle Ponds                                     |
+----------------------------+----------------------------------------------------------------+
| 9:00-noon                  | Vital rate modeling (Will)                                     |
|                            |                                                                |
|                            | Work session: Fit vital rate functions                         |
+----------------------------+----------------------------------------------------------------+
| noon-1:00                  | Lunch (bbcc)                                                   |
+----------------------------+----------------------------------------------------------------+
| 1:00-2:00                  | Field tour: Long-term marmot demography project (Emily Renkey) |
+----------------------------+----------------------------------------------------------------+
| 2:00-4:30                  | Field exercise: Implementing a demographic census (Paul)       |
+----------------------------+----------------------------------------------------------------+
| 4:30-6:00                  | Free time for socialization, exploration, rest, etc.           |
+----------------------------+----------------------------------------------------------------+
| 6:00-7:00                  | Dinner (bbcc)                                                  |
+----------------------------+----------------------------------------------------------------+
| 7:00-???                   | Social gathering *(optional)*                                  |
+----------------------------+----------------------------------------------------------------+

## Wednesday August 12: Workshop Day 3

Goals:

- Exposure to advanced IPM topics based on pre-course poll responses

- Finish a working draft of your own IPM

+----------------------------+------------------------------------------------------------------+
|                            |                                                                  |
+============================+==================================================================+
| 7:00-8:00                  | Breakfast (bbcc)                                                 |
+----------------------------+------------------------------------------------------------------+
| 8:00-9:00                  | Group walk                                                       |
+----------------------------+------------------------------------------------------------------+
| 9:00-noon                  | Advanced IPM topics (Will)                                       |
|                            |                                                                  |
|                            | - Environmental stochasticity                                    |
|                            |                                                                  |
|                            | - Density-dependence                                             |
|                            |                                                                  |
|                            | Work session: Finish building your IPM                           |
+----------------------------+------------------------------------------------------------------+
| noon-1:00                  | Lunch (bbcc)                                                     |
+----------------------------+------------------------------------------------------------------+
| 1:00-4:30                  | Field tour: Evolutionary ecology of *Ipomopsis* (Diane Campbell) |
|                            |                                                                  |
|                            | Field tour: Long-lived plant demography (David Inouye)           |
+----------------------------+------------------------------------------------------------------+
| 4:30-6:00                  | Free time for socialization, exploration, rest, etc.             |
+----------------------------+------------------------------------------------------------------+
| 6:00-7:00                  | Dinner (bbcc)                                                    |
+----------------------------+------------------------------------------------------------------+
| 7:00-???                   | Pack bags, clean out cabin                                       |
|                            |                                                                  |
|                            | Social gathering *(optional)*                                    |
+----------------------------+------------------------------------------------------------------+

## Thursday August 13: Departure Travel Day

+-----------------------------+----------------------------------------------------------+
|                             |                                                          |
+=============================+==========================================================+
| 4:30                        | Van transportation to Bustang in Crested Butte           |
+-----------------------------+----------------------------------------------------------+
| 5:15-11:10                  | Bustang to Denver Union Station                          |
+-----------------------------+----------------------------------------------------------+
| 11:30-                      | RTD "A" line transit to Denver airport; departure flight |
+-----------------------------+----------------------------------------------------------+
